// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WealthBackend.Data;

#nullable disable

namespace WealthBackend.Migrations
{
    [DbContext(typeof(WealthDbContext))]
    partial class WealthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WealthBackend.Models.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BalanceAsOf")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BalanceCurrent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryAssetCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WealthAssetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BalanceAsOf");

                    b.HasIndex("PrimaryAssetCategory");

                    b.HasIndex("WealthAssetType");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("WealthBackend.Models.AssetBalanceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BalanceAsOf")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BalanceAsOf");

                    b.HasIndex("AssetId", "BalanceAsOf")
                        .HasDatabaseName("IX_AssetBalanceHistory_AssetId_BalanceAsOf");

                    b.ToTable("AssetBalanceHistories", (string)null);
                });

            modelBuilder.Entity("WealthBackend.Models.AssetBalanceHistory", b =>
                {
                    b.HasOne("WealthBackend.Models.Asset", "Asset")
                        .WithMany("BalanceHistory")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("WealthBackend.Models.Asset", b =>
                {
                    b.Navigation("BalanceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
